### ISSUE TITLE
Current version of StencilStream is not compatible with newer oneapi versions as they are deployed on noctua2

### ISSUE THREAD

**Issue by typohnebild** [pc2/StencilStream#6]
One Problem is the use of a removed namespace:
https://github.com/pc2/StencilStream/blob/master/StencilStream/SingleQueueExecutor.hpp#L23
<CL/sycl/INTEL/fpga_extensions.hpp> is now
<sycl/ext/intel/fpga_extensions.hpp>
The second issue is that the to input kernels have the same name:
https://github.com/pc2/StencilStream/blob/master/StencilStream/MonotileExecutor.hpp#L130
https://github.com/pc2/StencilStream/blob/master/StencilStream/MonotileExecutor.hpp#L157
It looks to me that the later one is a OutputKernel :)

**Comment by JOOpdenhoevel** [comment]
Fixed in #8.
